export const PERMISSIONS = {
    READ_EMPLOYEE: 'READ_EMPLOYEE',
    CREATE_EMPLOYEE: 'CREATE_EMPLOYEE',
    UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
    DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
};

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
